name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.15.x, 1.16.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:

    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Allow skip provisioner tests
      uses: allenevans/set-env@v2.0.0
      with:
        ALLOW_PROVISIONER_SKIP: 1
        
    - name: Test
      run: go test ./...